# Generated by Django 4.2.13 on 2024-07-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0003_birthday_unique_person_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthday',
            name='image',
            field=models.ImageField(blank=True, upload_to='birthdays_images', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='birthday',
            name='last_name',
            field=models.CharField(blank=True, help_text='Опциональное поле', max_length=20, verbose_name='Фамилия'),
        ),
    ]
